//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ralid.Park.POS.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ralid.Park.POS.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 连接手持机设备失败 的本地化字符串。
        /// </summary>
        internal static string FrmMain_ConnectHandsetFail {
            get {
                return ResourceManager.GetString("FrmMain_ConnectHandsetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否需要导出参数? 的本地化字符串。
        /// </summary>
        internal static string FrmMain_ExportConfig {
            get {
                return ResourceManager.GetString("FrmMain_ExportConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出参数成功,手持机上的收费软件需要重启后参数才会生效 的本地化字符串。
        /// </summary>
        internal static string FrmMain_ExportConfigSuccess {
            get {
                return ResourceManager.GetString("FrmMain_ExportConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Fail {
            get {
                return ResourceManager.GetString("FrmMain_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到手持机设备，请确定是否已接上手持机设备 的本地化字符串。
        /// </summary>
        internal static string FrmMain_FindnotHandet {
            get {
                return ResourceManager.GetString("FrmMain_FindnotHandet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否需要导入授权记录? 的本地化字符串。
        /// </summary>
        internal static string FrmMain_ImportAuthenConfirm {
            get {
                return ResourceManager.GetString("FrmMain_ImportAuthenConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权记录数据导入状态 的本地化字符串。
        /// </summary>
        internal static string FrmMain_ImportAuthenLog {
            get {
                return ResourceManager.GetString("FrmMain_ImportAuthenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费记录数据导入状态 的本地化字符串。
        /// </summary>
        internal static string FrmMain_ImportCharges {
            get {
                return ResourceManager.GetString("FrmMain_ImportCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否需要导入收费记录? 的本地化字符串。
        /// </summary>
        internal static string FrmMain_ImportChargesComfirm {
            get {
                return ResourceManager.GetString("FrmMain_ImportChargesComfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总共需导入 的本地化字符串。
        /// </summary>
        internal static string FrmMain_ImportTotal {
            get {
                return ResourceManager.GetString("FrmMain_ImportTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有需要导入的授权记录 的本地化字符串。
        /// </summary>
        internal static string FrmMain_NoAuthenLog {
            get {
                return ResourceManager.GetString("FrmMain_NoAuthenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有需要导入的收费记录 的本地化字符串。
        /// </summary>
        internal static string FrmMain_NoCharges {
            get {
                return ResourceManager.GetString("FrmMain_NoCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询问 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Query {
            get {
                return ResourceManager.GetString("FrmMain_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Success {
            get {
                return ResourceManager.GetString("FrmMain_Success", resourceCulture);
            }
        }
    }
}
