#ifndef __CECONFIG_H__
#define __CECONFIG_H__
// CEFilter Component List:
#define CE_MODULES_COREDLL 1
#define CE_MODULES_KCOREDLL 1
#define CE_MODULES_NK 1
#define CE_MODULES_NKLOADER 1
#define CE_MODULES_OEM 1
#define CE_MODULES_OALIOCTL 1
#define CE_MODULES_FPCRT 1
#define CE_MODULES_CONSOLE 1
#define CE_MODULES_CMD 1
#define CE_MODULES_MSIM 1
#define CE_MODULES_COMMCTRL 1
#define CE_MODULES_COMMDLG 1
#define CE_MODULES_SHELL 1
#define CE_MODULES_LOADDBG 1
#define CE_MODULES_SHELLCELOG 1
#define CE_MODULES_RELFSD 1
#define CE_MODULES_WCETK 1
#define CE_MODULES_LPCD 1
#define CE_MODULES_LPCRT 1
#define CE_MODULES_NET 1
#define CE_MODULES_SECUR32 1
#define CE_MODULES_NTLMSSP 1
#define CE_MODULES_NTLMSSP_SVC 1
#define CE_MODULES_SPNEGO 1
#define CE_MODULES_SCHANNEL 1
#define CE_MODULES_CREDMAN 1
#define CE_MODULES_PRNPORT 1
#define CE_MODULES_PRNERR 1
#define CE_MODULES_NOTIFY 1
#define CE_MODULES_RNAAPP 1
#define CE_MODULES_CONNMC 1
#define CE_MODULES_NDISPWR 1
#define CE_MODULES_NETUI 1
#define CE_MODULES_ASYNCMAC 1
#define CE_MODULES_UNIMODEM 1
#define CE_MODULES_SERVICESD 1
#define CE_MODULES_SERVICESSTART 1
#define CE_MODULES_SERVICESENUM 1
#define CE_MODULES_SERVICES 1
#define CE_MODULES_TCPSTK 1
#define CE_MODULES_WINSOCK 1
#define CE_MODULES_AFD 1
#define CE_MODULES_WS2 1
#define CE_MODULES_WS2INSTL 1
#define CE_MODULES_WSPM 1
#define CE_MODULES_NSPM 1
#define CE_MODULES_WS2K 1
#define CE_MODULES_WS2SERV 1
#define CE_MODULES_SSLLSP 1
#define CE_MODULES_RTL8139 1
#define CE_MODULES_E100BEX 1
#define CE_MODULES_SMSC100FD 1
#define CE_MODULES_NE2000 1
#define CE_MODULES_DHCP 1
#define CE_MODULES_ETHMAN 1
#define CE_MODULES_PEGASSDN 1
#define CE_MODULES_AR6K_NDIS_SDIO 1
#define CE_MODULES_WZCSVC 1
#define CE_MODULES_WZCSAPI 1
#define CE_MODULES_ISLP2NDS 1
#define CE_MODULES_AR6K_NDIS_CF 1
#define CE_MODULES_WZCTOOL 1
#define CE_MODULES_EAPOL 1
#define CE_MODULES_EAP 1
#define CE_MODULES_EAPCHAP 1
#define CE_MODULES_EAPTLS 1
#define CE_MODULES_NETMUI 1
#define CE_MODULES_NDISUIO 1
#define CE_MODULES_VEIM 1
#define CE_MODULES_DHCPSRV 1
#define CE_MODULES_NDIS 1
#define CE_MODULES_AUTORAS 1
#define CE_MODULES_PPP 1
#define CE_MODULES_TAPI 1
#define CE_MODULES_RSAENH 1
#define CE_MODULES_CRYPT32 1
#define CE_MODULES_MSASN1 1
#define CE_MODULES_REDIR 1
#define CE_MODULES_NETBIOS 1
#define CE_MODULES_PING 1
#define CE_MODULES_IPCONFIG 1
#define CE_MODULES_TRACERT 1
#define CE_MODULES_ROUTE 1
#define CE_MODULES_NETSTAT 1
#define CE_MODULES_NDISCONFIG 1
#define CE_MODULES_IPSECCFG 1
#define CE_MODULES_IPHLPAPI 1
#define CE_MODULES_SOFTKB 1
#define CE_MODULES_SAMPLECAM 1
#define CE_MODULES_XAMLRUNTIME 1
#define CE_MODULES_HGCORE 1
#define CE_MODULES_XRRENDERERDDRAW 1
#define CE_MODULES_XRRENDEREROPENGL 1
#define CE_MODULES_GWES 1
#define CE_MODULES_KEYBD 1
#define CE_MODULES_POINTER 1
#define CE_MODULES_MGTT_O 1
#define CE_MODULES_DISPLAY 1
#define CE_MODULES_FONTS 1
#define CE_MODULES_TOUCHRECOGNIZER 1
#define CE_MODULES_PHYSICSENGINE 1
#define CE_MODULES_DDGUID 1
#define CE_MODULES_WAVEAPI 1
#define CE_MODULES_AUDIODRV 1
#define CE_MODULES_WAVESAMPLES 1
#define CE_MODULES_UIPROXY 1
#define CE_MODULES_CXPORT 1
#define CE_MODULES_BATTDRVR 1
#define CE_MODULES_NLEDDRVR 1
#define CE_MODULES_DEVICE 1
#define CE_MODULES_REGENUM 1
#define CE_MODULES_BUSENUM 1
#define CE_MODULES_PM 1
#define CE_MODULES_GIISR 1
#define CE_MODULES_MMTIMER 1
#define CE_MODULES_PCI 1
#define CE_MODULES_PCMCONV 1
#define CE_MODULES_SERIAL 1
#define CE_MODULES_PCCARD 1
#define CE_MODULES_8042KEYBOARD 1
#define CE_MODULES_NOPKEYBOARD 1
#define CE_MODULES_SDBUS 1
#define CE_MODULES_SDBUS2 1
#define CE_MODULES_SDMEMORY 1
#define CE_MODULES_USBHOST 1
#define CE_MODULES_USBD 1
#define CE_MODULES_USBOTG 1
#define CE_MODULES_USBHID 1
#define CE_MODULES_USBMSC 1
#define CE_MODULES_USBDISK6 1
#define CE_MODULES_HIDPARSE 1
#define CE_MODULES_KBDHID 1
#define CE_MODULES_CONSHID 1
#define CE_MODULES_MOUHID 1
#define CE_MODULES_USBFN 1
#define CE_MODULES_RNDISFN 1
#define CE_MODULES_SERIALUSBFN 1
#define CE_MODULES_CEDDK 1
#define CE_MODULES_EXFAT 1
#define CE_MODULES_FATUTIL 1
#define CE_MODULES_DISKCACHE 1
#define CE_MODULES_MSPART 1
#define CE_MODULES_ZLIB 1
#define CE_MODULES_XMLLITE 1
#define CE_MODULES_GB18030 1
#define CE_MODULES_FILESYS 1
#define CE_MODULES_FSDMGR 1
#define CE_MODULES_ROMFSD 1
#define CE_MODULES_TOOLHELP 1
#define CE_MODULES_VMINI 1
#define CE_MODULES_RT_TESTS 1
#define DCOM_MODULES_ATL 1
#define DCOM_MODULES_DLLHOST 1
#define DCOM_MODULES_DCOMSSD 1
#define DCOM_MODULES_RPCRT4 1
#define DCOM_MODULES_OLE32 1
#define DCOM_MODULES_OLEAUT32 1
#define DCOM_MODULES_UUID 1
#define DCOM_MODULES_OLEAUT32 1
#define GDIEX_MODULES_IMAGING 1
#define IE_MODULES_IEPEERS 1
#define IE_MODULES_IESAMPLE 1
#define IE_MODULES_IESAMPLE_EXR 1
#define IE_MODULES_TILEENGINE 1
#define IE_MODULES_TILEENGINERENDERPLUGIN 1
#define IE_MODULES_FLASHLITE 1
#define IE_MODULES_IECTL 1
#define IE_MODULES_MSLS31 1
#define IE_MODULES_MSHTML 1
#define IE_MODULES_SHDOCLC 1
#define IE_MODULES_SHDOCVW 1
#define IE_MODULES_INETCPL 1
#define IE_MODULES_MSXML3 1
#define IE_MODULES_URLMON 1
#define IE_MODULES_WININET 1
#define IE_MODULES_JSPROXY 1
#define IE_MODULES_SHLWAPI 1
#define IE_MODULES_UUID 1
#define IE_MODULES_IECEEXT 1
#define IE_MODULES_MLANG 1
#define SERVERS_MODULES_SMBSERVER 1
#define SERVERS_MODULES_SMBCONFIG 1
#define SERVERS_MODULES_FTPD 1
#define SERVERS_MODULES_REMOTEADMIN 1
#define SERVERS_MODULES_HTTPD 1
#define SERVERS_MODULES_TIMESVC 1
#define SERVERS_MODULES_RUI_COREUI 1
#define SERVERS_MODULES_RUI_HOSTNAME 1
#define SERVERS_MODULES_RUI_NETWORK 1
#define SERVERS_MODULES_RUI_PASSWORD 1
#define SERVERS_MODULES_RUI_VERSION 1
#define SERVERS_MODULES_RUI_ROOTDIRS 1
#define SERVERS_MODULES_RUI_SMBFILE 1
#define SERVERS_MODULES_RUI_SMBPRINT 1
#define SERVERS_MODULES_RUI_USERMANAGER 1
#define SERVERS_MODULES_RUI_RAS 1
#define SHELLSDK_MODULES_AYGSHELL 1
#define SHELL_MODULES_EXPLORER 1
#define SHELL_MODULES_SHCORE 1
#define SHELL_MODULES_CESHELL 1
#define SHELL_MODULES_VGAL 1
#define WCESHELLFE_MODULES_CONTROL 1
#define WCESHELLFE_MODULES_CTLPNL 1
#define WCESHELLFE_MODULES_CPLMAIN 1
#define WCESHELLFE_MODULES_ADVBACKLIGHT 1
#define WCESHELLFE_MODULES_CONNPNL 1
#define WCESHELLFE_MODULES_INTLL 1
#define WCESHELLFE_MODULES_STGUIL 1
#define WCESHELLFE_MODULES_STDWAVEFILES 1
#define DIRECTX_MODULES_STRMBASE 1
#define DIRECTX_MODULES_QUARTZ 1
#define DIRECTX_MODULES_MSACMCE 1
#define DIRECTX_MODULES_MSDMO 1
#define DIRECTX_MODULES_WMVDMOE 1
#define DATASYNC_MODULES_REPLLOG 1
#define DATASYNC_MODULES_RAPISRV 1
#define DATASYNC_MODULES_EVENTRST 1
#define DATASYNC_MODULES_RRA_STM 1
#define DATASYNC_MODULES_SYSTEMCPL 1
#define DATASYNC_MODULES_UDP2TCP 1
#define DATASYNC_MODULES_WCELOAD 1
#define DATASYNC_MODULES_UNLOAD 1
#define NETCFV2_MODULES_DOTNETV2 1
#define POWERVR_MODULES_SERVICES 1
#define POWERVR_MODULES_3DAPI 1
#define COREDLL_COREMAIN 1
#define COREDLL_THUNKS 1
#define COREDLL_LMEM 1
#define COREDLL_SHOWERR 1
#define COREDLL_CORECRT 1
#define COREDLL_CORESTRW 1
#define COREDLL_TNOTIFY 1
#define COREDLL_TAPILIB 1
#define COREDLL_CRYPTAPI 1
#define COREDLL_CORESIP 1
#define COREDLL_RECTAPI 1
#define COREDLL_WMGR_C 1
#define COREDLL_MGDI_C 1
#define COREDLL_ACCEL_C 1
#define COREDLL_MESSAGEDIALOGBOXTHUNK 1
#define COREDLL_SHCORE 1
#define COREDLL_SHCORE 1
#define COREDLL_PATH 1
#define COREDLL_SHORTCUT 1
#define COREDLL_SHEXEC 1
#define COREDLL_SHMISC 1
#define COREDLL_FILEOPEN 1
#define COREDLL_FILEINFO 1
#define COREDLL_SHELLAPIS 1
#define COREDLL_DSA 1
#define COREDLL_TIMEZONES 1
#define COREDLL_MMWAVE 1
#define COREDLL_MMSND 1
#define COREDLL_MMMIX 1
#define COREDLL_BATTERY 1
#define COREDLL_NLED 1
#define COREDLL_DEVENUM 1
#define COREDLL_DEVLOAD 1
#define COREDLL_FIBER 1
#define COREDLL_COREIMM 1
#define COREDLL_CORESIOA 1
#define COREDLL_CORESTRA 1
#define COREDLL_CORESIOW 1
#define COREDLL_FMTMSG 1
#define COREDLL_SERDEV 1
#define COREDLL_MULTIUI 1
#define COREDLL_CORELOC 1
#define COREDLL_CRT_CPP_EH_AND_RTTI 1
#define COREDLL_FULL_CRT 1
#define COREDLL_CRYPTHASH 1
#define COREDLL_RSA32 1
#define COREDLL_LMEM 1
#define COREDLL_SHOWERR 1
#define COREDLL_CORECRT 1
#define COREDLL_CORESTRW 1
#define COREDLL_TNOTIFY 1
#define COREDLL_TAPILIB 1
#define COREDLL_CRYPTAPI 1
#define COREDLL_CORESIP 1
#define COREDLL_RECTAPI 1
#define COREDLL_WMGR_C 1
#define COREDLL_MGDI_C 1
#define COREDLL_ACCEL_C 1
#define COREDLL_MESSAGEDIALOGBOXTHUNK 1
#define COREDLL_SHCORE 1
#define COREDLL_SHCORE 1
#define COREDLL_PATH 1
#define COREDLL_SHORTCUT 1
#define COREDLL_SHEXEC 1
#define COREDLL_SHMISC 1
#define COREDLL_FILEOPEN 1
#define COREDLL_FILEINFO 1
#define COREDLL_SHELLAPIS 1
#define COREDLL_DSA 1
#define COREDLL_TIMEZONES 1
#define COREDLL_MMWAVE 1
#define COREDLL_MMSND 1
#define COREDLL_MMMIX 1
#define COREDLL_BATTERY 1
#define COREDLL_NLED 1
#define COREDLL_DEVENUM 1
#define COREDLL_DEVLOAD 1
#define COREDLL_FIBER 1
#define COREDLL_COREIMM 1
#define COREDLL_CORESIOA 1
#define COREDLL_CORESTRA 1
#define COREDLL_CORESIOW 1
#define COREDLL_FMTMSG 1
#define COREDLL_SERDEV 1
#define COREDLL_MULTIUI 1
#define COREDLL_CORELOC 1
#define COREDLL_CRT_CPP_EH_AND_RTTI 1
#define COREDLL_FULL_CRT 1
#define COREDLL_CRYPTHASH 1
#define COREDLL_RSA32 1
#define KCOREDLL_KCOREMAIN 1
#define KCOREDLL_KTHUNKS 1
#define KCOREDLL_LMEM 1
#define KCOREDLL_SHOWERR 1
#define KCOREDLL_CORECRT 1
#define KCOREDLL_CORESTRW 1
#define KCOREDLL_TNOTIFY 1
#define KCOREDLL_TAPILIB 1
#define KCOREDLL_CRYPTAPI 1
#define KCOREDLL_CORESIP 1
#define KCOREDLL_RECTAPI 1
#define KCOREDLL_WMGR_C 1
#define KCOREDLL_MGDI_C 1
#define KCOREDLL_ACCEL_C 1
#define KCOREDLL_MESSAGEDIALOGBOXTHUNK 1
#define KCOREDLL_SHCORE 1
#define KCOREDLL_SHCORE 1
#define KCOREDLL_PATH 1
#define KCOREDLL_SHORTCUT 1
#define KCOREDLL_SHEXEC 1
#define KCOREDLL_SHMISC 1
#define KCOREDLL_FILEOPEN 1
#define KCOREDLL_FILEINFO 1
#define KCOREDLL_SHELLAPIS 1
#define KCOREDLL_DSA 1
#define KCOREDLL_TIMEZONES 1
#define KCOREDLL_MMWAVE 1
#define KCOREDLL_MMSND 1
#define KCOREDLL_MMMIX 1
#define KCOREDLL_BATTERY 1
#define KCOREDLL_NLED 1
#define KCOREDLL_DEVENUM 1
#define KCOREDLL_DEVLOAD 1
#define KCOREDLL_FIBER 1
#define KCOREDLL_COREIMM 1
#define KCOREDLL_CORESIOA 1
#define KCOREDLL_CORESTRA 1
#define KCOREDLL_CORESIOW 1
#define KCOREDLL_FMTMSG 1
#define KCOREDLL_SERDEV 1
#define KCOREDLL_MULTIUI 1
#define KCOREDLL_CORELOC 1
#define KCOREDLL_CRT_CPP_EH_AND_RTTI 1
#define KCOREDLL_FULL_CRT 1
#define KCOREDLL_CRYPTHASH 1
#define KCOREDLL_RSA32 1
#define KCOREDLL_LMEM 1
#define KCOREDLL_SHOWERR 1
#define KCOREDLL_CORECRT 1
#define KCOREDLL_CORESTRW 1
#define KCOREDLL_TNOTIFY 1
#define KCOREDLL_TAPILIB 1
#define KCOREDLL_CRYPTAPI 1
#define KCOREDLL_CORESIP 1
#define KCOREDLL_RECTAPI 1
#define KCOREDLL_WMGR_C 1
#define KCOREDLL_MGDI_C 1
#define KCOREDLL_ACCEL_C 1
#define KCOREDLL_MESSAGEDIALOGBOXTHUNK 1
#define KCOREDLL_SHCORE 1
#define KCOREDLL_SHCORE 1
#define KCOREDLL_PATH 1
#define KCOREDLL_SHORTCUT 1
#define KCOREDLL_SHEXEC 1
#define KCOREDLL_SHMISC 1
#define KCOREDLL_FILEOPEN 1
#define KCOREDLL_FILEINFO 1
#define KCOREDLL_SHELLAPIS 1
#define KCOREDLL_DSA 1
#define KCOREDLL_TIMEZONES 1
#define KCOREDLL_MMWAVE 1
#define KCOREDLL_MMSND 1
#define KCOREDLL_MMMIX 1
#define KCOREDLL_BATTERY 1
#define KCOREDLL_NLED 1
#define KCOREDLL_DEVENUM 1
#define KCOREDLL_DEVLOAD 1
#define KCOREDLL_FIBER 1
#define KCOREDLL_COREIMM 1
#define KCOREDLL_CORESIOA 1
#define KCOREDLL_CORESTRA 1
#define KCOREDLL_CORESIOW 1
#define KCOREDLL_FMTMSG 1
#define KCOREDLL_SERDEV 1
#define KCOREDLL_MULTIUI 1
#define KCOREDLL_CORELOC 1
#define KCOREDLL_CRT_CPP_EH_AND_RTTI 1
#define KCOREDLL_FULL_CRT 1
#define KCOREDLL_CRYPTHASH 1
#define KCOREDLL_RSA32 1
#define NK_NKCOMPR 1
#define NK_NKMAPFILE 1
#define NK_NKMSGQ 1
#define NK_OEMSTUB 1
#define NK_NKLOGGER 1
#define NKLOADER_NKLDR 1
#define OEM_NKSTUB 1
#define OEM_OEMMAIN 1
#define OEM_OEMMAIN_STATICKITL 1
#define COMMCTRL_TOOLBAR 1
#define COMMCTRL_UPDOWN 1
#define COMMCTRL_STATUS 1
#define COMMCTRL_PROPSHEET 1
#define COMMCTRL_LISTVIEW 1
#define COMMCTRL_TREEVIEW 1
#define COMMCTRL_DATE 1
#define COMMCTRL_TAB 1
#define COMMCTRL_PROGRESS 1
#define COMMCTRL_TRACKBAR 1
#define COMMCTRL_CAPEDIT 1
#define COMMCTRL_REBAR 1
#define COMMCTRL_CMDBAR 1
#define COMMCTRL_DSA 1
#define COMMCTRL_TOOLTIPS 1
#define COMMCTRL_FE 1
#define COMMCTRL_SHAPIS 1
#define NOTIFY_NOTIFPUB 1
#define NOTIFY_NOTIFUI 1
#define WINSOCK_SSLSOCK 1
#define PPP_PPP2SRVSTUB 1
#define GWES_GWE1 1
#define GWES_WMBASE 1
#define GWES_GWESHARE 1
#define GWES_GWESMAIN 1
#define GWES_IMMTHUNK 1
#define GWES_MSGQUE 1
#define GWES_GSETWINLONG 1
#define GWES_CEPTR 1
#define GWES_FOREGND 1
#define GWES_IDLE 1
#define GWES_KBDUI 1
#define GWES_UIBASE 1
#define GWES_MSGBEEP 1
#define GWES_AUDIO 1
#define GWES_GWE2 1
#define GWES_MGBASE 1
#define GWES_MGBITMAP 1
#define GWES_MGBLT 1
#define GWES_MGBLT2 1
#define GWES_MGDC 1
#define GWES_MGDIBSEC 1
#define GWES_MGDRAW 1
#define GWES_MGRGN 1
#define GWES_MGWINMGR 1
#define GWES_TCHUI 1
#define GWES_CALIBRUI 1
#define GWES_MGGRADFILL 1
#define GWES_MGALPHABLEND 1
#define GWES_MGTT 1
#define GWES_MGDRWTXT 1
#define GWES_MGPRINT 1
#define GWES_MGPAL 1
#define GWES_MGPALNAT 1
#define GWES_GWE3 1
#define GWES_ACCEL 1
#define GWES_BTNCTL 1
#define GWES_CARET 1
#define GWES_CASCADE 1
#define GWES_IMECTL 1
#define GWES_CLIPBD 1
#define GWES_CMBCTL 1
#define GWES_DEFWNDPROC 1
#define GWES_DLGMGR 1
#define GWES_DLGMNEM 1
#define GWES_EDCTL 1
#define GWES_GCACHE 1
#define GWES_GWECTRL 1
#define GWES_ICON 1
#define GWES_ICONCMN 1
#define GWES_IMGCTL 1
#define GWES_LBCTL 1
#define GWES_LOADBMP 1
#define GWES_LOADIMG 1
#define GWES_MENU 1
#define GWES_MENUSCRL 1
#define GWES_MNOOVER 1
#define GWES_MOUSEANDTOUCHCURSOR 1
#define GWES_ICONCURS 1
#define GWES_MCURSOR 1
#define GWES_MCURSOR8 1
#define GWES_CURSOR 1
#define GWES_CURSOR8 1
#define GWES_MNOTAPUI 1
#define GWES_TOUCHGESTURE 1
#define GWES_GESTUREANIMATION 1
#define GWES_PHYSICSWRAPPER 1
#define GWES_GWE4 1
#define GWES_NCLIENT 1
#define GWES_OOM 1
#define GWES_SBCMN 1
#define GWES_SCBCTL 1
#define GWES_STARTUP 1
#define GWES_STCCTL 1
#define GWES_WINMGR 1
#define GWES_STARTUI 1
#define GWES_OOMUI 1
#define GWES_SBCMNVIEWXP 1
#define GWES_NCLIENTVIEWXP 1
#define GWES_GCACHEVIEWXP 1
#define GWES_BTNCTLVIEWXP 1
#define GWES_STCCTLVIEWXP 1
#define GWES_CMBCTLVIEW 1
#define GWES_EDCTLVIEW 1
#define GWES_LBCTLVIEW 1
#define GWES_MENUVIEW 1
#define GWES_MSGBOX 1
#define GWES_MSGBOX_HPC 1
#define GWES_DLGMGR_HPC 1
#define GWES_MENU_HPC 1
#define GWES_CMBCTL_HPC 1
#define GWES_EDITCONTROLOS 1
#define GWES_TIMER 1
#define GWES_COLUMN 1
#define GWES_ATOM 1
#define GWES_DRAWMBAR 1
#define GWES_HOTKEY 1
#define GWES_SYSCOLOR 1
#define GWES_MGDX 1
#define GWES_MGALIAS 1
#define GWES_JOURNAL 1
#define GWES_MGTCI 1
#define FONTS_TAHOMA_1_07 1
#define FONTS_COUR_1_30 1
#define FONTS_WINGDING 1
#define FONTS_SIMSUN_2_50 1
#define WAVEAPI_WAPIWAVE 1
#define WAVEAPI_WAPIMAP 1
#define DEVICE_DEVCORE 1
#define DEVICE_IORM 1
#define DEVICE_PMIF 1
#define PM_PM_DEFAULT_PDD 1
#define PM_PM_MDD 1
#define PM_PM_PDD_COMMON 1
#define FATUTIL_FATUTIL_UI 1
#define FATUTIL_FATUTIL_MAIN 1
#define FATUTIL_EXFATUTIL 1
#define FILESYS_FSHEAP 1
#define FILESYS_FSMAIN 1
#define FILESYS_FSPROFILE 1
#define FILESYS_FSADVERTISE 1
#define FILESYS_FSYSRAM 1
#define FILESYS_FSREGHIVE 1
#define FILESYS_FSREPLBIT 1
#define FILESYS_FSDBASE 1
#define FILESYS_FSPASS 1
#define OLE32_DCOMOLE 1
#define OLE32_STG 1
#define OLEAUT32_OAALL 1
#define OLEAUT32_IDISPPROXY 1
#define OLEAUT32_OAALL 1
#define OLEAUT32_IDISPPROXY 1
#define IMAGING_IMG_PNG 1
#define IMAGING_IMG_LIBPNG 1
#define IMAGING_IMG_PNGENCODER 1
#define IMAGING_IMG_PNGDECODER 1
#define IMAGING_IMG_GIF 1
#define IMAGING_IMG_LIBLZW 1
#define IMAGING_IMG_GIFENCODER 1
#define IMAGING_IMG_GIFDECODER 1
#define IMAGING_IMG_JPEG 1
#define IMAGING_IMG_JPEGFULL 1
#define IMAGING_IMG_JPEGMEM 1
#define IMAGING_IMG_JPEGENCODER 1
#define IMAGING_IMG_JPEGDECODER 1
#define IMAGING_IMG_BMP 1
#define IMAGING_IMG_BMPENCODER 1
#define IMAGING_IMG_BMPDECODER 1
#define MSHTML_MSHTML_SDBIND 1
#define SHDOCVW_DOCHOST 1
#define SHDOCVW_DHEXT 1
#define SHDOCVW_SHDOCRES 1
#define INETCPL_INETCPL_IE 1
#define MSXML3_XMLDOM 1
#define MSXML3_XMLXQL 1
#define MSXML3_XMLNETFULL 1
#define URLMON_ZONES 1
#define WININET_PPSTUBS 1
#define SHLWAPI_SHLWIE 1
#define IECEEXT_IECEEXTMCOM 1
#define SMBSERVER_SMB_FILEFACTORY 1
#define HTTPD_HTTPISAPI 1
#define HTTPD_HTTPEXTN 1
#define HTTPD_HTTPAUTH 1
#define HTTPD_HTTPFILT 1
#define TIMESVC_TSVC_DST 1
#define AYGSHELL_AYGSHCORE 1
#define AYGSHELL_AYGSHHPC 1
#define AYGSHELL_AYGNQVGA 1
#define SHCORE_SHCORE 1
#define SHCORE_SHCORE 1
#define SHCORE_PATH 1
#define SHCORE_PATH 1
#define CESHELL_CESHAPI 1
#define CESHELL_CESHUI 1
#define CESHELL_TASKBARLIST 1
#define CPLMAIN_NETWORK 1
#define CPLMAIN_DATETIME 1
#define CPLMAIN_KEYBOARD 1
#define CPLMAIN_PASSWORD 1
#define CPLMAIN_OWNER 1
#define CPLMAIN_SYSTEM 1
#define CPLMAIN_DISPLAY 1
#define CPLMAIN_POINTERCMN 1
#define CPLMAIN_MOUSE 1
#define CPLMAIN_COMM 1
#define CPLMAIN_POWER 1
#define CPLMAIN_REMOVE 1
#define CPLMAIN_BACKLIGHT 1
#define CPLMAIN_COLORSCHEME 1
#define CPLMAIN_SOUNDS 1
#define CPLMAIN_DIALING 1
#define CPLMAIN_SIP 1
#define CPLMAIN_STYLUS 1
#define CPLMAIN_CERTS 1
#define QUARTZ_QUARTZ0 1
#define QUARTZ_AMUTIL 1
#define QUARTZ_FGCTL 1
#define QUARTZ_FILGRAPH 1
#define QUARTZ_QUARTZ1 1
#define QUARTZ_WAVEOUT 1
#define QUARTZ_ACMWRAP 1
#define QUARTZ_DMOWRAP 1
#define QUARTZ_QUARTZ2 1
#define QUARTZ_ASYNCRDR 1
#define QUARTZ_QTZBASE 1
#define QUARTZ_IMGSINK 1
#define QUARTZ_SMARTTEE 1
#define QUARTZ_QUARTZ3 1
#define QUARTZ_ASFWRITER 1
#define QUARTZ_ASFMUXCORE 1
#define QUARTZ_WAVEIN 1
#define QUARTZ_VIDCAP 1
#define QUARTZ_FILCAP 1
#define QUARTZ_SCMDOUT 1
#define QUARTZ_FILEREND 1
#define QUARTZ_WMT_STRMCORE 1
#define QUARTZ_WMT_SPLITTER 1
#define QUARTZ_WMT_FILESTRM 1
#define QUARTZ_QUARTZ4 1
#define QUARTZ_BUFFILTER 1
#define QUARTZ_COLOUR 1
#define QUARTZ_QUARTZ3 1
#define QUARTZ_ASFWRITER 1
#define QUARTZ_ASFMUXCORE 1
#define QUARTZ_WAVEIN 1
#define QUARTZ_VIDCAP 1
#define QUARTZ_FILCAP 1
#define QUARTZ_SCMDOUT 1
#define QUARTZ_FILEREND 1
#define QUARTZ_WMT_STRMCORE 1
#define QUARTZ_WMT_SPLITTER 1
#define QUARTZ_WMT_FILESTRM 1

// <SYSGENS>
// SYSGEN_ASYNCMAC
// SYSGEN_AS_BASE
// SYSGEN_ATL
// SYSGEN_AUDIO
// SYSGEN_AUDIO_STDWAVEFILES
// SYSGEN_AUTH
// SYSGEN_AUTH_NTLM
// SYSGEN_AUTH_SCHANNEL
// SYSGEN_AUTORAS
// SYSGEN_AYGSHELL
// SYSGEN_BATTERY
// SYSGEN_CAMERA_NULL
// SYSGEN_CEDDK
// SYSGEN_CERTS
// SYSGEN_CMD
// SYSGEN_CMEM
// SYSGEN_COMMCTRL
// SYSGEN_COMMDLG
// SYSGEN_CONNMC
// SYSGEN_CONSOLE
// SYSGEN_CORELOC
// SYSGEN_CORESTRA
// SYSGEN_CPP_EH_AND_RTTI
// SYSGEN_CREDMAN
// SYSGEN_CRYPTO
// SYSGEN_CS
// SYSGEN_CTLPNL
// SYSGEN_CURSOR
// SYSGEN_DCOM
// SYSGEN_DCOM_STG
// SYSGEN_DEVICE
// SYSGEN_DEVLOAD
// SYSGEN_DHCPSRV
// SYSGEN_DISPLAY
// SYSGEN_DOTNETV2
// SYSGEN_DOTNETV2_SUPPORT
// SYSGEN_DSHOW
// SYSGEN_DSHOW_ACMWRAP
// SYSGEN_DSHOW_CAPTURE
// SYSGEN_DSHOW_DISPLAY
// SYSGEN_DSHOW_DMO
// SYSGEN_DSHOW_WMT
// SYSGEN_DSPLINK
// SYSGEN_EAP
// SYSGEN_ETHERNET
// SYSGEN_ETH_80211
// SYSGEN_EXFAT
// SYSGEN_FATFS
// SYSGEN_FIBER
// SYSGEN_FMTMSG
// SYSGEN_FONTS_COUR_1_30
// SYSGEN_FONTS_SIMSUN_2_50
// SYSGEN_FONTS_TAHOMA_1_07
// SYSGEN_FONTS_WINGDING
// SYSGEN_FSDBASE
// SYSGEN_FSPASSWORD
// SYSGEN_FSRAMROM
// SYSGEN_FSREGHIVE
// SYSGEN_FSREPLBIT
// SYSGEN_FTPD
// SYSGEN_FULL_CRT
// SYSGEN_GB18030
// SYSGEN_GDI_ALPHABLEND
// SYSGEN_GESTUREANIMATION
// SYSGEN_GRADFILL
// SYSGEN_H264_DECODE_FILTER
// SYSGEN_HTTPD
// SYSGEN_IABASE
// SYSGEN_IE
// SYSGEN_IESAMPLE
// SYSGEN_IESAMPLE_EXR
// SYSGEN_IE_FLASHLITE
// SYSGEN_IE_JSCRIPT
// SYSGEN_IE_TILEENGINE
// SYSGEN_IMAGING
// SYSGEN_IMAGING_BMP_DECODE
// SYSGEN_IMAGING_BMP_ENCODE
// SYSGEN_IMAGING_GIF_DECODE
// SYSGEN_IMAGING_GIF_ENCODE
// SYSGEN_IMAGING_JPG_DECODE
// SYSGEN_IMAGING_JPG_ENCODE
// SYSGEN_IMAGING_PNG_DECODE
// SYSGEN_IMAGING_PNG_ENCODE
// SYSGEN_IMM
// SYSGEN_INETCPL
// SYSGEN_IPHLPAPI
// SYSGEN_JSCRIPT_AUTHOR
// SYSGEN_JSCRIPT_ENCODE
// SYSGEN_MINGDI
// SYSGEN_MINGWES
// SYSGEN_MININPUT
// SYSGEN_MINWMGR
// SYSGEN_MLANG
// SYSGEN_MODEM
// SYSGEN_MPEG2_DECODE_FILTER
// SYSGEN_MPEG4_DECODE_FILTER
// SYSGEN_MSGQUEUE
// SYSGEN_MSHTML
// SYSGEN_MSIM
// SYSGEN_MSPART
// SYSGEN_MSXML_DOM
// SYSGEN_MSXML_XQL
// SYSGEN_NDIS
// SYSGEN_NDISUIO
// SYSGEN_NETUTILS
// SYSGEN_NKCOMPR
// SYSGEN_NKMAPFILE
// SYSGEN_NLED
// SYSGEN_NOTIFY
// SYSGEN_OLE
// SYSGEN_OLE_GUIDS
// SYSGEN_OLE_STG
// SYSGEN_PHYSICSENGINE
// SYSGEN_PM
// SYSGEN_POWERVR
// SYSGEN_PPP
// SYSGEN_PRINTING
// SYSGEN_REDIR
// SYSGEN_RELFSD
// SYSGEN_REMOTECONFIG_FRAMEWORK
// SYSGEN_SDBUS
// SYSGEN_SD_MEMORY
// SYSGEN_SERDEV
// SYSGEN_SERVICES
// SYSGEN_SHDOCVW
// SYSGEN_SHELL
// SYSGEN_SMB_FILE
// SYSGEN_SMB_UI
// SYSGEN_SOFTKB
// SYSGEN_STANDARDSHELL
// SYSGEN_STDIO
// SYSGEN_STDIOA
// SYSGEN_STOREMGR
// SYSGEN_STOREMGR_CPL
// SYSGEN_STRSAFE
// SYSGEN_TAPI
// SYSGEN_TCPIP
// SYSGEN_TFAT
// SYSGEN_TIMESVC_DST
// SYSGEN_TIMM
// SYSGEN_TOOLHELP
// SYSGEN_TOUCH
// SYSGEN_TOUCHGESTURE
// SYSGEN_UIPROXY
// SYSGEN_UNIMODEM
// SYSGEN_URLMON
// SYSGEN_USB
// SYSGEN_USBFN
// SYSGEN_USBFN_ETHERNET
// SYSGEN_USBFN_SERIAL
// SYSGEN_USB_HID
// SYSGEN_USB_HID_CLIENTS
// SYSGEN_USB_HID_KEYBOARD
// SYSGEN_USB_HID_MOUSE
// SYSGEN_USB_STORAGE
// SYSGEN_VEM
// SYSGEN_WCELOAD
// SYSGEN_WCETK
// SYSGEN_WININET
// SYSGEN_WINSOCK
// SYSGEN_XAML_RUNTIME
// SYSGEN_XPSKIN
// </SYSGENS>
#endif
