//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECardInterface.ECardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ECardService.NightParkingSoap")]
    public interface NightParkingSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ECardInterface.ECardService.HelloWorldResponse HelloWorld(ECardInterface.ECardService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddParkingHistory", ReplyAction="*")]
        ECardInterface.ECardService.AddParkingHistoryResponse AddParkingHistory(ECardInterface.ECardService.AddParkingHistoryRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 messageContent 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParkingLotFullSMS", ReplyAction="*")]
        ECardInterface.ECardService.ParkingLotFullSMSResponse ParkingLotFullSMS(ECardInterface.ECardService.ParkingLotFullSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ECardInterface.ECardService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ECardInterface.ECardService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECardInterface.ECardService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ECardInterface.ECardService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddParkingHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddParkingHistory", Namespace="http://tempuri.org/", Order=0)]
        public ECardInterface.ECardService.AddParkingHistoryRequestBody Body;
        
        public AddParkingHistoryRequest() {
        }
        
        public AddParkingHistoryRequest(ECardInterface.ECardService.AddParkingHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddParkingHistoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int parkingSpaceApplicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string license;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime inTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime outTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double surplusTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string remarks;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string info1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string info2;
        
        public AddParkingHistoryRequestBody() {
        }
        
        public AddParkingHistoryRequestBody(string userID, int parkingSpaceApplicationID, string license, System.DateTime inTime, System.DateTime outTime, double surplusTime, string remarks, string info1, string info2) {
            this.userID = userID;
            this.parkingSpaceApplicationID = parkingSpaceApplicationID;
            this.license = license;
            this.inTime = inTime;
            this.outTime = outTime;
            this.surplusTime = surplusTime;
            this.remarks = remarks;
            this.info1 = info1;
            this.info2 = info2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddParkingHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddParkingHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECardInterface.ECardService.AddParkingHistoryResponseBody Body;
        
        public AddParkingHistoryResponse() {
        }
        
        public AddParkingHistoryResponse(ECardInterface.ECardService.AddParkingHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddParkingHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECardInterface.ECardService.ResultMessage AddParkingHistoryResult;
        
        public AddParkingHistoryResponseBody() {
        }
        
        public AddParkingHistoryResponseBody(ECardInterface.ECardService.ResultMessage AddParkingHistoryResult) {
            this.AddParkingHistoryResult = AddParkingHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParkingLotFullSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParkingLotFullSMS", Namespace="http://tempuri.org/", Order=0)]
        public ECardInterface.ECardService.ParkingLotFullSMSRequestBody Body;
        
        public ParkingLotFullSMSRequest() {
        }
        
        public ParkingLotFullSMSRequest(ECardInterface.ECardService.ParkingLotFullSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParkingLotFullSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string messageContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ECardInterface.ECardService.ArrayOfString userIDList;
        
        public ParkingLotFullSMSRequestBody() {
        }
        
        public ParkingLotFullSMSRequestBody(string messageContent, ECardInterface.ECardService.ArrayOfString userIDList) {
            this.messageContent = messageContent;
            this.userIDList = userIDList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParkingLotFullSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParkingLotFullSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECardInterface.ECardService.ParkingLotFullSMSResponseBody Body;
        
        public ParkingLotFullSMSResponse() {
        }
        
        public ParkingLotFullSMSResponse(ECardInterface.ECardService.ParkingLotFullSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParkingLotFullSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ECardInterface.ECardService.ResultMessage ParkingLotFullSMSResult;
        
        public ParkingLotFullSMSResponseBody() {
        }
        
        public ParkingLotFullSMSResponseBody(ECardInterface.ECardService.ResultMessage ParkingLotFullSMSResult) {
            this.ParkingLotFullSMSResult = ParkingLotFullSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NightParkingSoapChannel : ECardInterface.ECardService.NightParkingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NightParkingSoapClient : System.ServiceModel.ClientBase<ECardInterface.ECardService.NightParkingSoap>, ECardInterface.ECardService.NightParkingSoap {
        
        public NightParkingSoapClient() {
        }
        
        public NightParkingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NightParkingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NightParkingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NightParkingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECardInterface.ECardService.HelloWorldResponse ECardInterface.ECardService.NightParkingSoap.HelloWorld(ECardInterface.ECardService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ECardInterface.ECardService.HelloWorldRequest inValue = new ECardInterface.ECardService.HelloWorldRequest();
            inValue.Body = new ECardInterface.ECardService.HelloWorldRequestBody();
            ECardInterface.ECardService.HelloWorldResponse retVal = ((ECardInterface.ECardService.NightParkingSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECardInterface.ECardService.AddParkingHistoryResponse ECardInterface.ECardService.NightParkingSoap.AddParkingHistory(ECardInterface.ECardService.AddParkingHistoryRequest request) {
            return base.Channel.AddParkingHistory(request);
        }
        
        public ECardInterface.ECardService.ResultMessage AddParkingHistory(string userID, int parkingSpaceApplicationID, string license, System.DateTime inTime, System.DateTime outTime, double surplusTime, string remarks, string info1, string info2) {
            ECardInterface.ECardService.AddParkingHistoryRequest inValue = new ECardInterface.ECardService.AddParkingHistoryRequest();
            inValue.Body = new ECardInterface.ECardService.AddParkingHistoryRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.parkingSpaceApplicationID = parkingSpaceApplicationID;
            inValue.Body.license = license;
            inValue.Body.inTime = inTime;
            inValue.Body.outTime = outTime;
            inValue.Body.surplusTime = surplusTime;
            inValue.Body.remarks = remarks;
            inValue.Body.info1 = info1;
            inValue.Body.info2 = info2;
            ECardInterface.ECardService.AddParkingHistoryResponse retVal = ((ECardInterface.ECardService.NightParkingSoap)(this)).AddParkingHistory(inValue);
            return retVal.Body.AddParkingHistoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECardInterface.ECardService.ParkingLotFullSMSResponse ECardInterface.ECardService.NightParkingSoap.ParkingLotFullSMS(ECardInterface.ECardService.ParkingLotFullSMSRequest request) {
            return base.Channel.ParkingLotFullSMS(request);
        }
        
        public ECardInterface.ECardService.ResultMessage ParkingLotFullSMS(string messageContent, ECardInterface.ECardService.ArrayOfString userIDList) {
            ECardInterface.ECardService.ParkingLotFullSMSRequest inValue = new ECardInterface.ECardService.ParkingLotFullSMSRequest();
            inValue.Body = new ECardInterface.ECardService.ParkingLotFullSMSRequestBody();
            inValue.Body.messageContent = messageContent;
            inValue.Body.userIDList = userIDList;
            ECardInterface.ECardService.ParkingLotFullSMSResponse retVal = ((ECardInterface.ECardService.NightParkingSoap)(this)).ParkingLotFullSMS(inValue);
            return retVal.Body.ParkingLotFullSMSResult;
        }
    }
}
