//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutDoorLEDTool {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutDoorLEDTool.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 汽车 的本地化字符串。
        /// </summary>
        internal static string CarType_Car {
            get {
                return ResourceManager.GetString("CarType_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电单车 的本地化字符串。
        /// </summary>
        internal static string CarType_Motor {
            get {
                return ResourceManager.GetString("CarType_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入口 的本地化字符串。
        /// </summary>
        internal static string Entrance_In {
            get {
                return ResourceManager.GetString("Entrance_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出口 的本地化字符串。
        /// </summary>
        internal static string Entrance_Out {
            get {
                return ResourceManager.GetString("Entrance_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询问 的本地化字符串。
        /// </summary>
        internal static string Form_Query {
            get {
                return ResourceManager.GetString("Form_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请设置卡片类型 的本地化字符串。
        /// </summary>
        internal static string FrmAreaDetail_EmptyCardType {
            get {
                return ResourceManager.GetString("FrmAreaDetail_EmptyCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请设置车位数 的本地化字符串。
        /// </summary>
        internal static string FrmAreaDetail_EmptyCarport {
            get {
                return ResourceManager.GetString("FrmAreaDetail_EmptyCarport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请设置满位颜色 的本地化字符串。
        /// </summary>
        internal static string FrmAreaDetail_EmptyFullColor {
            get {
                return ResourceManager.GetString("FrmAreaDetail_EmptyFullColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择余位颜色 的本地化字符串。
        /// </summary>
        internal static string FrmAreaDetail_EmptyVacantColor {
            get {
                return ResourceManager.GetString("FrmAreaDetail_EmptyVacantColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车位数不能小于余位数 的本地化字符串。
        /// </summary>
        internal static string FrmAreaDetail_InvalidCarport {
            get {
                return ResourceManager.GetString("FrmAreaDetail_InvalidCarport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接设置有误，连接不上数据库 的本地化字符串。
        /// </summary>
        internal static string FrmConnect_SQLConnectedFail {
            get {
                return ResourceManager.GetString("FrmConnect_SQLConnectedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请设置波特率 的本地化字符串。
        /// </summary>
        internal static string FrmLEDDetail_EmptyBaudRate {
            get {
                return ResourceManager.GetString("FrmLEDDetail_EmptyBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请设置小车屏地址 的本地化字符串。
        /// </summary>
        internal static string FrmLEDDetail_EmptyCarLedAddress {
            get {
                return ResourceManager.GetString("FrmLEDDetail_EmptyCarLedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请设置串口号 的本地化字符串。
        /// </summary>
        internal static string FrmLEDDetail_EmptyCommport {
            get {
                return ResourceManager.GetString("FrmLEDDetail_EmptyCommport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请设置电单车屏地址 的本地化字符串。
        /// </summary>
        internal static string FrmLEDDetail_EmptyMotorLedAddress {
            get {
                return ResourceManager.GetString("FrmLEDDetail_EmptyMotorLedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置信息保存成功 的本地化字符串。
        /// </summary>
        internal static string FrmMain_SaveSuccess {
            get {
                return ResourceManager.GetString("FrmMain_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Setting {
            get {
                return ResourceManager.GetString("FrmMain_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除所选项? 的本地化字符串。
        /// </summary>
        internal static string FrmMain_SureDelete {
            get {
                return ResourceManager.GetString("FrmMain_SureDelete", resourceCulture);
            }
        }
    }
}
