//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceTestProject.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterfaceReturnCode", Namespace="http://schemas.datacontract.org/2004/07/Ralid.Park.WebService")]
    public enum InterfaceReturnCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParameterError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseNoRecord = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseSaveDataError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CannotConnectDatabase = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPlaceAccess = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InterfaceException = 255,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSCardPaymentInfo", Namespace="http://schemas.datacontract.org/2004/07/Ralid.Park.WebService")]
    [System.SerializableAttribute()]
    public partial class WSCardPaymentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarPlateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChargeDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrDiscountHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntranceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastTotalFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TariffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeIntervalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarPlate {
            get {
                return this.CarPlateField;
            }
            set {
                if ((object.ReferenceEquals(this.CarPlateField, value) != true)) {
                    this.CarPlateField = value;
                    this.RaisePropertyChanged("CarPlate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID {
            get {
                return this.CardIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIDField, value) != true)) {
                    this.CardIDField = value;
                    this.RaisePropertyChanged("CardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChargeDateTime {
            get {
                return this.ChargeDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargeDateTimeField, value) != true)) {
                    this.ChargeDateTimeField = value;
                    this.RaisePropertyChanged("ChargeDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrDiscountHour {
            get {
                return this.CurrDiscountHourField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrDiscountHourField, value) != true)) {
                    this.CurrDiscountHourField = value;
                    this.RaisePropertyChanged("CurrDiscountHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountField, value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterDateTime {
            get {
                return this.EnterDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterDateTimeField, value) != true)) {
                    this.EnterDateTimeField = value;
                    this.RaisePropertyChanged("EnterDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntranceName {
            get {
                return this.EntranceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntranceNameField, value) != true)) {
                    this.EntranceNameField = value;
                    this.RaisePropertyChanged("EntranceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastTotalFee {
            get {
                return this.LastTotalFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.LastTotalFeeField, value) != true)) {
                    this.LastTotalFeeField = value;
                    this.RaisePropertyChanged("LastTotalFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paid {
            get {
                return this.PaidField;
            }
            set {
                if ((object.ReferenceEquals(this.PaidField, value) != true)) {
                    this.PaidField = value;
                    this.RaisePropertyChanged("Paid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tariff {
            get {
                return this.TariffField;
            }
            set {
                if ((object.ReferenceEquals(this.TariffField, value) != true)) {
                    this.TariffField = value;
                    this.RaisePropertyChanged("Tariff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeInterval {
            get {
                return this.TimeIntervalField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeIntervalField, value) != true)) {
                    this.TimeIntervalField = value;
                    this.RaisePropertyChanged("TimeInterval");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IParkWebService")]
    public interface IParkWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardByID", ReplyAction="http://tempuri.org/IParkWebService/GetCardByIDResponse")]
        Ralid.Park.BusinessModel.Result.QueryResult<Ralid.Park.BusinessModel.Model.CardInfo> GetCardByID(string cardID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/SaveCard", ReplyAction="http://tempuri.org/IParkWebService/SaveCardResponse")]
        InterfaceTestProject.ServiceReference1.InterfaceReturnCode SaveCard(string cardID, short cardNum, byte carType, byte status, short index, int lastEntrance, string activationDate, System.DateTime validDate, decimal balance, decimal deposit, int discountHour, int options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/SaveCard2", ReplyAction="http://tempuri.org/IParkWebService/SaveCard2Response")]
        Ralid.Park.BusinessModel.Result.CommandResult SaveCard2(Ralid.Park.BusinessModel.Model.CardInfo card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/DeleteCard", ReplyAction="http://tempuri.org/IParkWebService/DeleteCardResponse")]
        Ralid.Park.BusinessModel.Result.CommandResult DeleteCard(string cardID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetVacant", ReplyAction="http://tempuri.org/IParkWebService/GetVacantResponse")]
        short GetVacant(int parkid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/SetVacant", ReplyAction="http://tempuri.org/IParkWebService/SetVacantResponse")]
        InterfaceTestProject.ServiceReference1.InterfaceReturnCode SetVacant(int parkid, int vacant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardLastPayment", ReplyAction="http://tempuri.org/IParkWebService/GetCardLastPaymentResponse")]
        decimal GetCardLastPayment(Ralid.Park.BusinessModel.Model.CardInfo info, Ralid.Park.BusinessModel.Model.OperatorInfo operatorInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardChargeRecords", ReplyAction="http://tempuri.org/IParkWebService/GetCardChargeRecordsResponse")]
        Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardChargeRecord> GetCardChargeRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardDeferRecords", ReplyAction="http://tempuri.org/IParkWebService/GetCardDeferRecordsResponse")]
        Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardDeferRecord> GetCardDeferRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardLostRestoreRecords", ReplyAction="http://tempuri.org/IParkWebService/GetCardLostRestoreRecordsResponse")]
        Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardLostRestoreRecord> GetCardLostRestoreRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardDisableEnableRecords", ReplyAction="http://tempuri.org/IParkWebService/GetCardDisableEnableRecordsResponse")]
        Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardDisableEnableRecord> GetCardDisableEnableRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardRecycleRecords", ReplyAction="http://tempuri.org/IParkWebService/GetCardRecycleRecordsResponse")]
        Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardRecycleRecord> GetCardRecycleRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardReleaseRecords", ReplyAction="http://tempuri.org/IParkWebService/GetCardReleaseRecordsResponse")]
        Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardReleaseRecord> GetCardReleaseRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardDeleteRecords", ReplyAction="http://tempuri.org/IParkWebService/GetCardDeleteRecordsResponse")]
        Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardDeleteRecord> GetCardDeleteRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetAllEntraces", ReplyAction="http://tempuri.org/IParkWebService/GetAllEntracesResponse")]
        Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.EntranceInfo> GetAllEntraces();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardStatusByCardID", ReplyAction="http://tempuri.org/IParkWebService/GetCardStatusByCardIDResponse")]
        Ralid.Park.BusinessModel.Enum.CardStatus GetCardStatusByCardID(string cardID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/QueryParkByCarPlate", ReplyAction="http://tempuri.org/IParkWebService/QueryParkByCarPlateResponse")]
        Ralid.Park.BusinessModel.Result.QueryResult<Ralid.Park.BusinessModel.Model.ParkInfo> QueryParkByCarPlate(string carPlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetAllPark", ReplyAction="http://tempuri.org/IParkWebService/GetAllParkResponse")]
        Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.ParkInfo> GetAllPark();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/GetCardPayment", ReplyAction="http://tempuri.org/IParkWebService/GetCardPaymentResponse")]
        Ralid.Park.BusinessModel.Result.QueryResult<InterfaceTestProject.ServiceReference1.WSCardPaymentInfo> GetCardPayment(string cardID, string discountHour, string discountAmount, string reserve1, string reserve2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkWebService/CardFeePay", ReplyAction="http://tempuri.org/IParkWebService/CardFeePayResponse")]
        Ralid.Park.BusinessModel.Result.CommandResult CardFeePay(string cardID, string chargeDateTime, string paid, string payMode, string memo, string reserve1, string reserve2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParkWebServiceChannel : InterfaceTestProject.ServiceReference1.IParkWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParkWebServiceClient : System.ServiceModel.ClientBase<InterfaceTestProject.ServiceReference1.IParkWebService>, InterfaceTestProject.ServiceReference1.IParkWebService {
        
        public ParkWebServiceClient() {
        }
        
        public ParkWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParkWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResult<Ralid.Park.BusinessModel.Model.CardInfo> GetCardByID(string cardID) {
            return base.Channel.GetCardByID(cardID);
        }
        
        public InterfaceTestProject.ServiceReference1.InterfaceReturnCode SaveCard(string cardID, short cardNum, byte carType, byte status, short index, int lastEntrance, string activationDate, System.DateTime validDate, decimal balance, decimal deposit, int discountHour, int options) {
            return base.Channel.SaveCard(cardID, cardNum, carType, status, index, lastEntrance, activationDate, validDate, balance, deposit, discountHour, options);
        }
        
        public Ralid.Park.BusinessModel.Result.CommandResult SaveCard2(Ralid.Park.BusinessModel.Model.CardInfo card) {
            return base.Channel.SaveCard2(card);
        }
        
        public Ralid.Park.BusinessModel.Result.CommandResult DeleteCard(string cardID) {
            return base.Channel.DeleteCard(cardID);
        }
        
        public short GetVacant(int parkid) {
            return base.Channel.GetVacant(parkid);
        }
        
        public InterfaceTestProject.ServiceReference1.InterfaceReturnCode SetVacant(int parkid, int vacant) {
            return base.Channel.SetVacant(parkid, vacant);
        }
        
        public decimal GetCardLastPayment(Ralid.Park.BusinessModel.Model.CardInfo info, Ralid.Park.BusinessModel.Model.OperatorInfo operatorInfo) {
            return base.Channel.GetCardLastPayment(info, operatorInfo);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardChargeRecord> GetCardChargeRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search) {
            return base.Channel.GetCardChargeRecords(search);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardDeferRecord> GetCardDeferRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search) {
            return base.Channel.GetCardDeferRecords(search);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardLostRestoreRecord> GetCardLostRestoreRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search) {
            return base.Channel.GetCardLostRestoreRecords(search);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardDisableEnableRecord> GetCardDisableEnableRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search) {
            return base.Channel.GetCardDisableEnableRecords(search);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardRecycleRecord> GetCardRecycleRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search) {
            return base.Channel.GetCardRecycleRecords(search);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardReleaseRecord> GetCardReleaseRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search) {
            return base.Channel.GetCardReleaseRecords(search);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.CardDeleteRecord> GetCardDeleteRecords(Ralid.Park.BusinessModel.SearchCondition.RecordSearchCondition search) {
            return base.Channel.GetCardDeleteRecords(search);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.EntranceInfo> GetAllEntraces() {
            return base.Channel.GetAllEntraces();
        }
        
        public Ralid.Park.BusinessModel.Enum.CardStatus GetCardStatusByCardID(string cardID) {
            return base.Channel.GetCardStatusByCardID(cardID);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResult<Ralid.Park.BusinessModel.Model.ParkInfo> QueryParkByCarPlate(string carPlate) {
            return base.Channel.QueryParkByCarPlate(carPlate);
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResultList<Ralid.Park.BusinessModel.Model.ParkInfo> GetAllPark() {
            return base.Channel.GetAllPark();
        }
        
        public Ralid.Park.BusinessModel.Result.QueryResult<InterfaceTestProject.ServiceReference1.WSCardPaymentInfo> GetCardPayment(string cardID, string discountHour, string discountAmount, string reserve1, string reserve2) {
            return base.Channel.GetCardPayment(cardID, discountHour, discountAmount, reserve1, reserve2);
        }
        
        public Ralid.Park.BusinessModel.Result.CommandResult CardFeePay(string cardID, string chargeDateTime, string paid, string payMode, string memo, string reserve1, string reserve2) {
            return base.Channel.CardFeePay(cardID, chargeDateTime, paid, payMode, memo, reserve1, reserve2);
        }
    }
}
