//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ralid.Park.UserControls.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ralid.Park.UserControls.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 通行权限 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_Access {
            get {
                return ResourceManager.GetString("CardGridHeader_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生效日期 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_ActivationDate {
            get {
                return ResourceManager.GetString("CardGridHeader_ActivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片余额 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_Balance {
            get {
                return ResourceManager.GetString("CardGridHeader_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满位允许 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_CanEnterWhenFull {
            get {
                return ResourceManager.GetString("CardGridHeader_CanEnterWhenFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_CardID {
            get {
                return ResourceManager.GetString("CardGridHeader_CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片状态 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_CardStatus {
            get {
                return ResourceManager.GetString("CardGridHeader_CardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片类型 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_CardType {
            get {
                return ResourceManager.GetString("CardGridHeader_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌号码 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_CarPlate {
            get {
                return ResourceManager.GetString("CardGridHeader_CarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_CarType {
            get {
                return ResourceManager.GetString("CardGridHeader_CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_Certificate {
            get {
                return ResourceManager.GetString("CardGridHeader_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期允许 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_EnableWhenExpired {
            get {
                return ResourceManager.GetString("CardGridHeader_EnableWhenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节假日 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_HolidayEnabled {
            get {
                return ResourceManager.GetString("CardGridHeader_HolidayEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持卡人 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_OwnerName {
            get {
                return ResourceManager.GetString("CardGridHeader_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否在场 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_ParkingFlag {
            get {
                return ResourceManager.GetString("CardGridHeader_ParkingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复入场 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_RepeatIn {
            get {
                return ResourceManager.GetString("CardGridHeader_RepeatIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复出场 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_RepeatOut {
            get {
                return ResourceManager.GetString("CardGridHeader_RepeatOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期限 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_ValidDate {
            get {
                return ResourceManager.GetString("CardGridHeader_ValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车位计数 的本地化字符串。
        /// </summary>
        internal static string CardGridHeader_WithCount {
            get {
                return ResourceManager.GetString("CardGridHeader_WithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有权限 的本地化字符串。
        /// </summary>
        internal static string FunctionTree_Root {
            get {
                return ResourceManager.GetString("FunctionTree_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有停车场 的本地化字符串。
        /// </summary>
        internal static string HardwareTree_Root {
            get {
                return ResourceManager.GetString("HardwareTree_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时卡数量不多 的本地化字符串。
        /// </summary>
        internal static string HardwareTree_TempCardAlarm {
            get {
                return ResourceManager.GetString("HardwareTree_TempCardAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时卡数量不多，请加卡 的本地化字符串。
        /// </summary>
        internal static string HardwareTree_TempCardSpeech {
            get {
                return ResourceManager.GetString("HardwareTree_TempCardSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生效日期不能早于2011年1月1日 的本地化字符串。
        /// </summary>
        internal static string UcCard_InvalidActivationDate {
            get {
                return ResourceManager.GetString("UcCard_InvalidActivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号不是整型,或者卡号超出最大位数 的本地化字符串。
        /// </summary>
        internal static string UcCard_InvalidCardID {
            get {
                return ResourceManager.GetString("UcCard_InvalidCardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一种卡片类型 的本地化字符串。
        /// </summary>
        internal static string UcCard_InvalidCardType {
            get {
                return ResourceManager.GetString("UcCard_InvalidCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌号码过长，请重新输入 的本地化字符串。
        /// </summary>
        internal static string UcCard_InvalidCarPlate {
            get {
                return ResourceManager.GetString("UcCard_InvalidCarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一种车型 的本地化字符串。
        /// </summary>
        internal static string UcCard_InvalidCarType {
            get {
                return ResourceManager.GetString("UcCard_InvalidCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生效日期不能晚于2099年12月31日 的本地化字符串。
        /// </summary>
        internal static string UcCard_InvalidMaxActivationDate {
            get {
                return ResourceManager.GetString("UcCard_InvalidMaxActivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效日期不能晚于2099年12月31日 的本地化字符串。
        /// </summary>
        internal static string UcCard_InvalidMaxValidDate {
            get {
                return ResourceManager.GetString("UcCard_InvalidMaxValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车主姓名不能为空 的本地化字符串。
        /// </summary>
        internal static string UcCard_InvalidOwnerName {
            get {
                return ResourceManager.GetString("UcCard_InvalidOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效日期不能早于2011年1月1日 的本地化字符串。
        /// </summary>
        internal static string UcCard_InvalidValidDate {
            get {
                return ResourceManager.GetString("UcCard_InvalidValidDate", resourceCulture);
            }
        }
    }
}
