//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfflineCardPayingTool.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfflineCardPayingTool.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 启用写卡模式 的本地化字符串。
        /// </summary>
        internal static string EnableWriteCard {
            get {
                return ResourceManager.GetString("EnableWriteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加 的本地化字符串。
        /// </summary>
        internal static string Form_Add {
            get {
                return ResourceManager.GetString("Form_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意 的本地化字符串。
        /// </summary>
        internal static string Form_Alert {
            get {
                return ResourceManager.GetString("Form_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel文档|*.xls|所有文件(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string Form_ExcelFilter {
            get {
                return ResourceManager.GetString("Form_ExcelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要关闭此窗口吗？ 的本地化字符串。
        /// </summary>
        internal static string Form_ExitQuery {
            get {
                return ResourceManager.GetString("Form_ExitQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要“退出系统”吗？点击 &quot;确定&quot; 将关闭停车场系统，点击 &quot;取消&quot; 返回。 的本地化字符串。
        /// </summary>
        internal static string Form_ExitSystemQuery {
            get {
                return ResourceManager.GetString("Form_ExitSystemQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询问 的本地化字符串。
        /// </summary>
        internal static string Form_Query {
            get {
                return ResourceManager.GetString("Form_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存到电子表格时出现错误！ 的本地化字符串。
        /// </summary>
        internal static string Form_SaveExcelFail {
            get {
                return ResourceManager.GetString("Form_SaveExcelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Form_Stop {
            get {
                return ResourceManager.GetString("Form_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片数据无效！ 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_CardDataErr {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_CardDataErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片已锁定 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_CardDisabled {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_CardDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片已过期 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_CardExpired {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_CardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片已挂失 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_CardLoss {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_CardLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片已注销 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_CardRecycled {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_CardRecycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片未到生效期 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_CardUnActivate {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_CardUnActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此操作会把卡片的缴费信息清除，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_DeletePayment {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_DeletePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已缴费，请在{0}分钟内离场！ 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_FreeRemain {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_FreeRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读卡器没有找到缴费卡片，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_NotCard {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_NotCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非收费卡片！ 的本地化字符串。
        /// </summary>
        internal static string FrmCardCenterCharge_NotPaymentCard {
            get {
                return ResourceManager.GetString("FrmCardCenterCharge_NotPaymentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消的收费信息:卡号{0} 收费时间{1} 入场时间{2} 收费金额{3} 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_CancelPaymentAlarm {
            get {
                return ResourceManager.GetString("FrmCardPaying_CancelPaymentAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此操作会把卡片上次收费记录删除,是否继续? 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_CancelPaymentQuey {
            get {
                return ResourceManager.GetString("FrmCardPaying_CancelPaymentQuey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}有车等待入场 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_CardWaitEnterSpeech {
            get {
                return ResourceManager.GetString("FrmCardPaying_CardWaitEnterSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}车牌对比失败 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_CardWaitExitSpeech {
            get {
                return ResourceManager.GetString("FrmCardPaying_CardWaitExitSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中央收费处 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_CentralCharge {
            get {
                return ResourceManager.GetString("FrmCardPaying_CentralCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实收金额不大于零，是否继续? 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_MoneyLittleQuery {
            get {
                return ResourceManager.GetString("FrmCardPaying_MoneyLittleQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实收金额大于应收金额，是否继续？ 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_MoneyMuchQuery {
            get {
                return ResourceManager.GetString("FrmCardPaying_MoneyMuchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非临时卡片 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_NotTempCard {
            get {
                return ResourceManager.GetString("FrmCardPaying_NotTempCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在收费请稍候 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_Paying {
            get {
                return ResourceManager.GetString("FrmCardPaying_Paying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应收{0}元 的本地化字符串。
        /// </summary>
        internal static string FrmCardPaying_PayingSpeech {
            get {
                return ResourceManager.GetString("FrmCardPaying_PayingSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或者密码输入不正确! 的本地化字符串。
        /// </summary>
        internal static string FrmLoginTool_AuthenFail {
            get {
                return ResourceManager.GetString("FrmLoginTool_AuthenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空! 的本地化字符串。
        /// </summary>
        internal static string FrmLoginTool_InvalidPwd {
            get {
                return ResourceManager.GetString("FrmLoginTool_InvalidPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空! 的本地化字符串。
        /// </summary>
        internal static string FrmLoginTool_InvalidUserName {
            get {
                return ResourceManager.GetString("FrmLoginTool_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员:{0} 的本地化字符串。
        /// </summary>
        internal static string FrmOfflineCardPaying_lblOperator {
            get {
                return ResourceManager.GetString("FrmOfflineCardPaying_lblOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时间:{0} 的本地化字符串。
        /// </summary>
        internal static string FrmOfflineCardPaying_lblStartFrom {
            get {
                return ResourceManager.GetString("FrmOfflineCardPaying_lblStartFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前工作站:{0} 的本地化字符串。
        /// </summary>
        internal static string FrmOfflineCardPaying_lblStation {
            get {
                return ResourceManager.GetString("FrmOfflineCardPaying_lblStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置当前工作站! 的本地化字符串。
        /// </summary>
        internal static string FrmOfflineCardPaying_NotWorkStationID {
            get {
                return ResourceManager.GetString("FrmOfflineCardPaying_NotWorkStationID", resourceCulture);
            }
        }
    }
}
