//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ralid.Park.UserControls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ralid.Park.UserControls.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通行权限.
        /// </summary>
        internal static string CardGridHeader_Access {
            get {
                return ResourceManager.GetString("CardGridHeader_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生效日期.
        /// </summary>
        internal static string CardGridHeader_ActivationDate {
            get {
                return ResourceManager.GetString("CardGridHeader_ActivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片余额.
        /// </summary>
        internal static string CardGridHeader_Balance {
            get {
                return ResourceManager.GetString("CardGridHeader_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 满位允许.
        /// </summary>
        internal static string CardGridHeader_CanEnterWhenFull {
            get {
                return ResourceManager.GetString("CardGridHeader_CanEnterWhenFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡号.
        /// </summary>
        internal static string CardGridHeader_CardID {
            get {
                return ResourceManager.GetString("CardGridHeader_CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片状态.
        /// </summary>
        internal static string CardGridHeader_CardStatus {
            get {
                return ResourceManager.GetString("CardGridHeader_CardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片类型.
        /// </summary>
        internal static string CardGridHeader_CardType {
            get {
                return ResourceManager.GetString("CardGridHeader_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车牌号码.
        /// </summary>
        internal static string CardGridHeader_CarPlate {
            get {
                return ResourceManager.GetString("CardGridHeader_CarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车型.
        /// </summary>
        internal static string CardGridHeader_CarType {
            get {
                return ResourceManager.GetString("CardGridHeader_CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片编号.
        /// </summary>
        internal static string CardGridHeader_Certificate {
            get {
                return ResourceManager.GetString("CardGridHeader_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门.
        /// </summary>
        internal static string CardGridHeader_Department {
            get {
                return ResourceManager.GetString("CardGridHeader_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过期允许.
        /// </summary>
        internal static string CardGridHeader_EnableWhenExpired {
            get {
                return ResourceManager.GetString("CardGridHeader_EnableWhenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节假日.
        /// </summary>
        internal static string CardGridHeader_HolidayEnabled {
            get {
                return ResourceManager.GetString("CardGridHeader_HolidayEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名单类型.
        /// </summary>
        internal static string CardGridHeader_ListType {
            get {
                return ResourceManager.GetString("CardGridHeader_ListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 持卡人.
        /// </summary>
        internal static string CardGridHeader_OwnerName {
            get {
                return ResourceManager.GetString("CardGridHeader_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否在场.
        /// </summary>
        internal static string CardGridHeader_ParkingFlag {
            get {
                return ResourceManager.GetString("CardGridHeader_ParkingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复入场.
        /// </summary>
        internal static string CardGridHeader_RepeatIn {
            get {
                return ResourceManager.GetString("CardGridHeader_RepeatIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复出场.
        /// </summary>
        internal static string CardGridHeader_RepeatOut {
            get {
                return ResourceManager.GetString("CardGridHeader_RepeatOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效期限.
        /// </summary>
        internal static string CardGridHeader_ValidDate {
            get {
                return ResourceManager.GetString("CardGridHeader_ValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车位计数.
        /// </summary>
        internal static string CardGridHeader_WithCount {
            get {
                return ResourceManager.GetString("CardGridHeader_WithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有权限.
        /// </summary>
        internal static string FunctionTree_Root {
            get {
                return ResourceManager.GetString("FunctionTree_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有停车场.
        /// </summary>
        internal static string HardwareTree_Root {
            get {
                return ResourceManager.GetString("HardwareTree_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 临时卡数量不多.
        /// </summary>
        internal static string HardwareTree_TempCardAlarm {
            get {
                return ResourceManager.GetString("HardwareTree_TempCardAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 临时卡数量不多，请加卡.
        /// </summary>
        internal static string HardwareTree_TempCardSpeech {
            get {
                return ResourceManager.GetString("HardwareTree_TempCardSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 型号.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需添加硬币.
        /// </summary>
        internal static string UCAPMMonitor_NeedAddCoin {
            get {
                return ResourceManager.GetString("UCAPMMonitor_NeedAddCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脱机卡片的储值余额不能大于167772.15.
        /// </summary>
        internal static string UcCard_BalanceOver {
            get {
                return ResourceManager.GetString("UcCard_BalanceOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生效日期不能早于2011年1月1日.
        /// </summary>
        internal static string UcCard_InvalidActivationDate {
            get {
                return ResourceManager.GetString("UcCard_InvalidActivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡号不是整型，或者卡号超出最大位数.
        /// </summary>
        internal static string UcCard_InvalidCardID {
            get {
                return ResourceManager.GetString("UcCard_InvalidCardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一种卡片类型.
        /// </summary>
        internal static string UcCard_InvalidCardType {
            get {
                return ResourceManager.GetString("UcCard_InvalidCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车牌号码为空，或者车牌号码过长，请重新输入.
        /// </summary>
        internal static string UcCard_InvalidCarPlate {
            get {
                return ResourceManager.GetString("UcCard_InvalidCarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一种车型.
        /// </summary>
        internal static string UcCard_InvalidCarType {
            get {
                return ResourceManager.GetString("UcCard_InvalidCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生效日期不能晚于2099年12月31日.
        /// </summary>
        internal static string UcCard_InvalidMaxActivationDate {
            get {
                return ResourceManager.GetString("UcCard_InvalidMaxActivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效日期不能晚于2099年12月31日.
        /// </summary>
        internal static string UcCard_InvalidMaxValidDate {
            get {
                return ResourceManager.GetString("UcCard_InvalidMaxValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车主姓名不能为空.
        /// </summary>
        internal static string UcCard_InvalidOwnerName {
            get {
                return ResourceManager.GetString("UcCard_InvalidOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效日期不能早于2011年1月1日.
        /// </summary>
        internal static string UcCard_InvalidValidDate {
            get {
                return ResourceManager.GetString("UcCard_InvalidValidDate", resourceCulture);
            }
        }
    }
}
