//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ralid.Park.BLL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ralid.Park.BLL.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缴费机编号 &quot;{0}&quot; 已经被使用.
        /// </summary>
        internal static string APMBll_NumbeUsed {
            get {
                return ResourceManager.GetString("APMBll_NumbeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡号:{0} 收费:{1} 入场:{2} 费用:{3} 实收:{4} 说明:{5}.
        /// </summary>
        internal static string CardBll_CancelPaymentDescr {
            get {
                return ResourceManager.GetString("CardBll_CancelPaymentDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已发行的,非临时的卡片不能删除!.
        /// </summary>
        internal static string CardBll_CannotDelelt {
            get {
                return ResourceManager.GetString("CardBll_CannotDelelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已发行的,非临时的卡片不能删除.
        /// </summary>
        internal static string CardBll_CannotDelete {
            get {
                return ResourceManager.GetString("CardBll_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已存在卡号为 &quot;{0}&quot;  的名单！.
        /// </summary>
        internal static string CardBll_CardIDbeUsed {
            get {
                return ResourceManager.GetString("CardBll_CardIDbeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片挂失.
        /// </summary>
        internal static string CardBll_CardLost {
            get {
                return ResourceManager.GetString("CardBll_CardLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动生成卡号失败，请重新发行！.
        /// </summary>
        internal static string CardBll_CreateListCardIDFail {
            get {
                return ResourceManager.GetString("CardBll_CreateListCardIDFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片收费记录不唯一.
        /// </summary>
        internal static string CardPaymentRecordBll_notSingle {
            get {
                return ResourceManager.GetString("CardPaymentRecordBll_notSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步时间间隔设置不正确，要设置成大于零的值.
        /// </summary>
        internal static string DatetimeSyncService_Invalidtime {
            get {
                return ResourceManager.GetString("DatetimeSyncService_Invalidtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强制删除.
        /// </summary>
        internal static string Mandate_Delete {
            get {
                return ResourceManager.GetString("Mandate_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作员 &quot;{0}&quot; 是系统默认的操作员,不能被删除.
        /// </summary>
        internal static string OperatorBll_CannotDelete {
            get {
                return ResourceManager.GetString("OperatorBll_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作员ID &quot;{0}&quot; 已经被使用.
        /// </summary>
        internal static string OperatorBll_IDbeUsed {
            get {
                return ResourceManager.GetString("OperatorBll_IDbeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作员真实姓名 &quot;{0}&quot; 已经被使用.
        /// </summary>
        internal static string OperatorBll_NamebeUsed {
            get {
                return ResourceManager.GetString("OperatorBll_NamebeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库中不存在操作员 &quot;{0}&quot; ,可能被其它人员删除.
        /// </summary>
        internal static string OperatorBll_NotExistsOperator {
            get {
                return ResourceManager.GetString("OperatorBll_NotExistsOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作员编号 &quot;{0}&quot; 已经被使用.
        /// </summary>
        internal static string OperatorBll_NumbeUsed {
            get {
                return ResourceManager.GetString("OperatorBll_NumbeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成汇总结果时没有指定操作员.
        /// </summary>
        internal static string OperatorSettleBLL_noOperator {
            get {
                return ResourceManager.GetString("OperatorSettleBLL_noOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色 &quot;{0}&quot;  是系统默认角色,不能删除.
        /// </summary>
        internal static string RoleBll_CannotDelete {
            get {
                return ResourceManager.GetString("RoleBll_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有操作员归属到角色 &quot;{0}&quot; ,请先把角色为 &quot;{1}&quot; 的操作员删除或改成别的角色,再来删除此角色!.
        /// </summary>
        internal static string RoleBll_RoleBeUsed {
            get {
                return ResourceManager.GetString("RoleBll_RoleBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作站 &quot;{0} &quot;是系统默认工作站,不能删除.
        /// </summary>
        internal static string WorkstationBll_CannotDelete {
            get {
                return ResourceManager.GetString("WorkstationBll_CannotDelete", resourceCulture);
            }
        }
    }
}
